version: '${DOCKER_COMPOSE_VERSION:-3}' # if version not set, use 3

# https://github.com/codesshaman/inception/blob/main/01_INSTALL_SOFT.md

volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: /home/rvan-duy/data/mariadb
  html:
    driver_opts:
      type: none
      o: bind
      device: /home/rvan-duy/data/wordpress

services:
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - html:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - DB_NAME=${DB_NAME:?DB_NAME is missing}
      - DB_HOST=${DB_HOST:?DB_HOST is missing}
      - DB_USER=${DB_USER:?DB_USER is missing}
      - DB_PASS=${DB_PASS:?DB_PASS is missing}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME:?WP_ADMIN_NAME is missing}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS:?WP_ADMIN_PASS is missing}
      - WP_USER_NAME=${WP_USER_NAME:?WP_USER_NAME is missing}
      - WP_USER_PASS=${WP_USER_PASS:?WP_USER_PASS is missing}

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "test", "-e", "/mytestyfile.txt" ]
      interval: 5s
    environment:
      - DB_NAME=${DB_NAME:?DB_NAME is missing}
      - DB_HOST=${DB_HOST:?DB_HOST is missing}
      - DB_USER=${DB_USER:?DB_USER is missing}
      - DB_PASS=${DB_PASS:?DB_PASS is missing}

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx
    volumes:
      - html:/var/www/html
    ports:
      - "443:443"
    environment:
      - COUNTRY_CODE=${COUNTRY_CODE:?COUNTRY_CODE is missing}
      - STATE=${STATE:?STATE is missing}
      - LOCALITY_NAME=${LOCALITY_NAME:?LOCALITY_NAME is missing}
      - ORGANIZATION=${ORGANIZATION:?ORGANIZATION is missing}
      - ORGANIZATION_UNIT=${ORGANIZATION_UNIT:?ORGANIZATION_UNIT is missing}
      - COMMON_NAME=${COMMON_NAME:?COMMON_NAME is missing}
