version: '${DOCKER_COMPOSE_VERSION:-3}' # if version not set, use 3


volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: /home/rvan-duy/data/mariadb
  html:
    driver_opts:
      type: none
      o: bind
      device: /home/rvan-duy/data/wordpress


services:
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - html:/var/www/html
    ports:
      - "80:80"
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    environment:
      - DATABASE_NAME=${DATABASE_NAME:-default_database_name}
      - ADMIN_NAME=${ADMIN_NAME:?This variable is required to set the admin user for the MariaDB service.}
      - ADMIN_PASS=${ADMIN_PASS:?This variable is required to set the admin user for the MariaDB service.}
      - USER_NAME=${USER_NAME:?This variable is required to set the regular user for the MariaDB service.}
      - USER_PASS=${USER_PASS:?This variable is required to set the regular user for the MariaDB service.}


  # nginx:
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
